### ISSUE TITLE
B站会员购票务使用了新版验证码，老方法失效了

### ISSUE THREAD

**Issue by duobuhui** [Hobr/bilibili_show_selenium_deprecate#31]
今天抢方舟fes的时候发现老的过验证码方式失效了，叔叔现在换了验证码模块，[fengx1a0](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order) 这个大佬的工具基本失效了，只能自己手动过验证码之后，才能继续15分钟的抢票。在他那提了issue，他还没有回复。请问您能解决这个问题吗

**Comment by Hobr** [comment]
我这个脚本已经很老了，而且写成了屎山不再维护，这段时间可能会做一个油猴脚本出来。fengx1a0因为黄牛用他的脚本所以不再开源了，有兴趣等他发闭源版本可以加群818884376

**Comment by Hobr** [comment]
左转[Just-Prog/Bilibili_show_ticket_auto_order](https://github.com/Just-Prog/Bilibili_show_ticket_auto_order)
